const abs = {
  exercises: [
    {
      equipment: "Cable",
      exercise_type: "Strength",
      // experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Cable Crunch",
      primary_muscles: "Abs",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      // experience: "Advanced",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Hanging Leg Raise",
      primary_muscles: "Abs",
      secondary_muscles: "['Forearms']",
    },
    {
      equipment: "Other",
      exercise_type: "Strength",
      // experience: "Intermediate",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Weighted Crunch",
      primary_muscles: "Abs",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Isolation",
      name: "Lying Floor Leg Raise",
      primary_muscles: "Abs",
      secondary_muscles: "[]",
    },

    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Static",
      mechanics: "Isolation",
      name: "Plank",
      primary_muscles: "Abs",
      secondary_muscles: "['Lower Back']",
    },

    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Dumbbell Side Bends",
      primary_muscles: "Abs",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Static",
      mechanics: "Isolation",
      name: "Side Plank",
      primary_muscles: "Abs",
      secondary_muscles: "['Lower Back']",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Isolation",
      name: "Ab Crunch",
      primary_muscles: "Abs",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Decline Sit Up",
      primary_muscles: "Abs",
      secondary_muscles: "[]",
    },
    {
      equipment: "Barbell",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "N/A",
      mechanics: "Compound",
      name: "Abdominal Barbell Rollouts",
      primary_muscles: "Abs",
      secondary_muscles: "['Shoulders']",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Isolation",
      name: "Sit Up",
      primary_muscles: "Abs",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Pull",
      mechanics: "Compound",
      name: "Twisting Hanging Knee Raise",
      primary_muscles: "Abs",
      secondary_muscles: "['Forearms']",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Floor Crunch (legs on bench)",
      primary_muscles: "Abs",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Russian Twist",
      primary_muscles: "Abs",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Isometric",
      mechanics: "Compound",
      name: "Rotating Mountain Climber",
      primary_muscles: "Abs",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Abdominal Air Bike (AKA Bicycle)",
      primary_muscles: "Abs",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Pull",
      mechanics: "Compound",
      name: "Hanging Knee Raise",
      primary_muscles: "Abs",
      secondary_muscles: "['Forearms']",
    },
    {
      equipment: "Exercise Ball",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Exercise Ball Crunch",
      primary_muscles: "Abs",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Lying Floor Knee Tuck",
      primary_muscles: "Abs",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Isometric",
      mechanics: "Compound",
      name: "Plank to Hip Raise",
      primary_muscles: "Abs",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Isometric",
      mechanics: "Compound",
      name: "Alternate Straight Leg Lower",
      primary_muscles: "Abs",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Pull (Bilateral)",
      mechanics: "Isolation",
      name: "Standing Stomach Vacuum",
      primary_muscles: "Abs",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Compound",
      name: "Side Crunch With Leg Lift",
      primary_muscles: "Abs",
      secondary_muscles: "[]",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Isometric",
      mechanics: "Compound",
      name: "Pallof Press",
      primary_muscles: "Abs",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "N/A",
      mechanics: "Isolation",
      name: "Chair Leg Raise",
      primary_muscles: "Abs",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "N/A",
      mechanics: "Isolation",
      name: "Abominal Hip Thrust",
      primary_muscles: "Abs",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Isolation",
      name: "Straight Leg Toe Touch (Floor Toe Reach)",
      primary_muscles: "Abs",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Isometric",
      mechanics: "Compound",
      name: "Dead Bug",
      primary_muscles: "Abs",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Compound",
      name: "Seated Leg Tucks",
      primary_muscles: "Abs",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "N/A",
      mechanics: "Compound",
      name: "Bench Jack Knife",
      primary_muscles: "Abs",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "N/A",
      mechanics: "Isolation",
      name: "Lying Alternate Floor Leg Raise",
      primary_muscles: "Abs",
      secondary_muscles: "[]",
    },
    {
      equipment: "Barbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "N/A",
      mechanics: "Isolation",
      name: "Seated Barbell Twist",
      primary_muscles: "Abs",
      secondary_muscles: "[]",
    },
    {
      equipment: "Kettle Bells",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Turkish Get Up",
      primary_muscles: "Abs",
      secondary_muscles:
        "['Adductors', 'Glutes', 'Hamstrings', 'Quads', 'Shoulders', 'Upper Back']",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "N/A",
      mechanics: "Isolation",
      name: "Lying Bench Leg Raise",
      primary_muscles: "Abs",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Twisting Bench Crunch",
      primary_muscles: "Abs",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Advanced",
      force_type: "Isometric",
      mechanics: "Compound",
      name: "Dragon Flag",
      primary_muscles: "Abs",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "N/A",
      mechanics: "Compound",
      name: "Decline Abdominal Reach",
      primary_muscles: "Abs",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "N/A",
      mechanics: "Isolation",
      name: "Decline Bench Leg Raise",
      primary_muscles: "Abs",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Isolation",
      name: "Frog Sit Up",
      primary_muscles: "Abs",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Static",
      mechanics: "Isolation",
      name: "Plank With Feet On Bench",
      primary_muscles: "Abs",
      secondary_muscles: "['Lower Back']",
    },
  ],
  num_exercises: 40,
};
