const biceps = {
  exercises: [
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Standing Dumbbell Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Barbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Standing Barbell Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Isolation",
      name: "Incline Dumbbell Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "['Forearms']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Standing Hammer Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "['Forearms']",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Cable Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Barbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "EZ Bar Preacher Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Unilateral)",
      mechanics: "Isolation",
      name: "Concentration Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "['Forearms']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Pull (Bilateral)",
      mechanics: "Isolation",
      name: "Zottman Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "['Forearms']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Hammer Curl Across The Body AKA Pinwheel Curls",
      primary_muscles: "Biceps",
      secondary_muscles: "['Forearms']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Alternating Standing Dumbbell Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "['Forearms']",
    },
    {
      equipment: "Barbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "EZ Bar Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Cable Curl (Rope Extension)",
      primary_muscles: "Biceps",
      secondary_muscles: "['Forearms']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Alternate Seated Dumbbell Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Machine",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Machine Bicep Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Barbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Barbell Preacher Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Seated Dumbbell Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Barbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Spider Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Isolation",
      name: "Standing Dumbbell Reverse Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "['Forearms']",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Standing High Pulley Cable Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Isolation",
      name: "Dumbbell Preacher Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "['Forearms']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Alternate Standing Hammer Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "['Forearms']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "One Arm Seated Dumbbell Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Cable Preacher Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "One Arm Standing Hammer Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "['Forearms']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Seated Hammer Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "['Forearms']",
    },
    {
      equipment: "Barbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Isolation",
      name: "Barbell Drag Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "['Forearms']",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "One-Arm Cable Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Dumbbell Hammer Preacher Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "['Forearms']",
    },
    {
      equipment: "Machine",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Lat Pulldown Bicep Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Barbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Seated Barbell Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Barbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Wide Grip Standing Barbell Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Isolation",
      name: "Standing Dumbbell Drag Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "['Forearms']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Isolation",
      name: "Seated Zottman Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "['Forearms']",
    },
    {
      equipment: "Barbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Barbell hammer Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "['Forearms']",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Lying Cable Curl (floor)",
      primary_muscles: "Biceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Alternate Incline Dumbbell Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "One Arm Standing Dumbbell Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Isolation",
      name: "Seated Dumbbell Reverse Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "['Forearms']",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Squatting Cable Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "One Arm Dumbbell Preacher Curl",
      primary_muscles: "Biceps",
      secondary_muscles: "[]",
    },
  ],
  num_exercises: 40,
};
