const chest = {
  exercises: [
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Dumbbell Bench Press",
      primary_muscles: "Chest",
      secondary_muscles: "['Shoulders', 'Triceps']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Push",
      mechanics: "Compound",
      name: "Dumbbell Pullover",
      primary_muscles: "Chest",
      secondary_muscles: "['Lats', 'Shoulders', 'Triceps']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Incline Dumbbell Bench Press",
      primary_muscles: "Chest",
      secondary_muscles: "['Shoulders', 'Triceps']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Isolation",
      name: "Dumbbell Flys",
      primary_muscles: "Chest",
      secondary_muscles: "['Shoulders', 'Triceps']",
    },
    {
      equipment: "Barbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Incline Bench Press",
      primary_muscles: "Chest",
      secondary_muscles: "['Shoulders', 'Triceps']",
    },
    {
      equipment: "Barbell",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Barbell Bench Press",
      primary_muscles: "Chest",
      secondary_muscles: "['Shoulders', 'Triceps']",
    },
    {
      equipment: "Machine",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push",
      mechanics: "Isolation",
      name: "Pec Dec",
      primary_muscles: "Chest",
      secondary_muscles: "['Shoulders']",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Isolation",
      name: "Standing Cable Fly",
      primary_muscles: "Chest",
      secondary_muscles: "['Shoulders', 'Triceps']",
    },
    {
      equipment: "Machine",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Hammer Strength Bench Press",
      primary_muscles: "Chest",
      secondary_muscles: "['Shoulders', 'Triceps']",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push",
      mechanics: "Isolation",
      name: "Cable Crossovers (Upper Chest)",
      primary_muscles: "Chest",
      secondary_muscles: "['Shoulders']",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Chest Dip",
      primary_muscles: "Chest",
      secondary_muscles: "['Abs', 'Shoulders', 'Triceps']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Close Grip Dumbbell Press (AKA Crush Press)",
      primary_muscles: "Chest",
      secondary_muscles: "['Shoulders', 'Triceps']",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Isolation",
      name: "Cable Iron Cross",
      primary_muscles: "Chest",
      secondary_muscles: "['Shoulders', 'Triceps']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push",
      mechanics: "Isolation",
      name: "Incline Dumbbell Flys",
      primary_muscles: "Chest",
      secondary_muscles: "['Shoulders', 'Triceps']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push",
      mechanics: "Compound",
      name: "Reverse Grip Dumbbell Bench Press",
      primary_muscles: "Chest",
      secondary_muscles: "['Shoulders', 'Triceps']",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Push Up",
      primary_muscles: "Chest",
      secondary_muscles: "['Abs', 'Shoulders', 'Triceps']",
    },
    {
      equipment: "Barbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Decline Bench Press",
      primary_muscles: "Chest",
      secondary_muscles: "['Shoulders', 'Triceps']",
    },
    {
      equipment: "Machine",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Hammer Strength Machine Incline Bench Press",
      primary_muscles: "Chest",
      secondary_muscles: "['Chest', 'Shoulders']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Decline Dumbbell Bench Press",
      primary_muscles: "Chest",
      secondary_muscles: "['Shoulders', 'Triceps']",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Push (Bilateral)",
      mechanics: "Isolation",
      name: "Standing Low to High Cable Fly",
      primary_muscles: "Chest",
      secondary_muscles: "['Shoulders', 'Triceps']",
    },
    {
      equipment: "Machine",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push",
      mechanics: "Compound",
      name: "Smith Machine Incline Bench Press",
      primary_muscles: "Chest",
      secondary_muscles: "['Shoulders', 'Triceps']",
    },
    {
      equipment: "Other",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Push",
      mechanics: "Compound",
      name: "Weighted Chest Dip",
      primary_muscles: "Chest",
      secondary_muscles: "['Shoulders', 'Triceps']",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Isolation",
      name: "Standing High to Low Cable Fly",
      primary_muscles: "Chest",
      secondary_muscles: "['Shoulders', 'Triceps']",
    },
    {
      equipment: "Bench",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Decline Push Up (Feet on Bench)",
      primary_muscles: "Chest",
      secondary_muscles: "['Abs', 'Shoulders', 'Triceps']",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Advanced",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Plyometric Push Up",
      primary_muscles: "Chest",
      secondary_muscles: "['Abs', 'Shoulders', 'Triceps']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Isolation",
      name: "Decline Dumbbell Flys",
      primary_muscles: "Chest",
      secondary_muscles: "['Shoulders', 'Triceps']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Unilateral)",
      mechanics: "Isolation",
      name: "One Arm Dumbbell Fly",
      primary_muscles: "Chest",
      secondary_muscles: "['Shoulders', 'Triceps']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Neutral Grip Dumbbell Bench Press",
      primary_muscles: "Chest",
      secondary_muscles: "['Shoulders', 'Triceps']",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Stretch Push Up (On Risers)",
      primary_muscles: "Chest",
      secondary_muscles: "['Abs', 'Shoulders', 'Triceps']",
    },
    {
      equipment: "Barbell",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Pull",
      mechanics: "Compound",
      name: "Barbell Pullover",
      primary_muscles: "Chest",
      secondary_muscles: "['Lats', 'Shoulders', 'Triceps']",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Cable Chest Press",
      primary_muscles: "Chest",
      secondary_muscles: "['Shoulders', 'Triceps']",
    },
    {
      equipment: "Machine",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push",
      mechanics: "Compound",
      name: "Smith Machine Bench Press",
      primary_muscles: "Chest",
      secondary_muscles: "['Shoulders', 'Triceps']",
    },
    {
      equipment: "Kettle Bells",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Unilateral)",
      mechanics: "Compound",
      name: "One Arm Kettlebell Bench Press",
      primary_muscles: "Chest",
      secondary_muscles: "['Abs', 'Shoulders', 'Triceps']",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Isolation",
      name: "Incline Cable Flys",
      primary_muscles: "Chest",
      secondary_muscles: "['Shoulders', 'Triceps']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Dumbbell Bench Press Rotational Grip",
      primary_muscles: "Chest",
      secondary_muscles: "['Shoulders', 'Triceps']",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Paused Push Up",
      primary_muscles: "Chest",
      secondary_muscles: "['Abs', 'Shoulders', 'Triceps']",
    },
    {
      equipment: "Bench",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Reverse Grip Incline Push Up",
      primary_muscles: "Chest",
      secondary_muscles: "['Abs', 'Shoulders', 'Triceps']",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Straight Bar Dip",
      primary_muscles: "Chest",
      secondary_muscles: "['Shoulders', 'Triceps']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Neutral Grip Incline Dumbbell Bench Press",
      primary_muscles: "Chest",
      secondary_muscles: "['Shoulders', 'Triceps']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push",
      mechanics: "Compound",
      name: "One-Arm Dumbbell Bench Press",
      primary_muscles: "Chest",
      secondary_muscles: "['Shoulders', 'Triceps']",
    },
  ],
  num_exercises: 40,
};
