const lats = {
  exercises: [
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Lat Pull Down",
      primary_muscles: "Lats",
      secondary_muscles: "['Abs', 'Biceps', 'Shoulders', 'Upper Back']",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Close Grip Lat Pull Down",
      primary_muscles: "Lats",
      secondary_muscles: "['Abs', 'Biceps', 'Shoulders', 'Upper Back']",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Wide Grip Pull Up",
      primary_muscles: "Lats",
      secondary_muscles: "['Abs', 'Biceps', 'Shoulders', 'Upper Back']",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Chin Up",
      primary_muscles: "Lats",
      secondary_muscles: "['Abs', 'Biceps', 'Shoulders', 'Upper Back']",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Straight Arm Lat Pull Down",
      primary_muscles: "Lats",
      secondary_muscles: "['Abs', 'Biceps', 'Shoulders', 'Upper Back']",
    },
    {
      equipment: "Machine",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Wide Grip Lat Pull Down",
      primary_muscles: "Lats",
      secondary_muscles: "['Abs', 'Biceps', 'Shoulders', 'Upper Back']",
    },
    {
      equipment: "Machine",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Reverse Grip Lat Pull Down (Underhand)",
      primary_muscles: "Lats",
      secondary_muscles: "['Abs', 'Biceps', 'Shoulders', 'Upper Back']",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Pull Up",
      primary_muscles: "Lats",
      secondary_muscles: "['Abs', 'Biceps', 'Shoulders', 'Upper Back']",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Compound",
      name: "V-Bar Pull Up",
      primary_muscles: "Lats",
      secondary_muscles: "['Biceps', 'Middle Back', 'Shoulders']",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Rope Straight Arm Pull Down",
      primary_muscles: "Lats",
      secondary_muscles: "['Abs', 'Biceps', 'Shoulders', 'Upper Back']",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "V-Bar Pull Down",
      primary_muscles: "Lats",
      secondary_muscles: "['Abs', 'Biceps', 'Shoulders', 'Upper Back']",
    },
    {
      equipment: "Chains",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Weighted Pull Up",
      primary_muscles: "Lats",
      secondary_muscles: "['Abs', 'Biceps', 'Shoulders', 'Upper Back']",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Unilateral)",
      mechanics: "Compound",
      name: "Shotgun Row",
      primary_muscles: "Lats",
      secondary_muscles:
        "['Abs', 'Biceps', 'Shoulders', 'Traps', 'Upper Back']",
    },
    {
      equipment: "Bands",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Press (Bilateral)",
      mechanics: "Compound",
      name: "Band Assisted Chin Up (From Foot)",
      primary_muscles: "Lats",
      secondary_muscles: "['Abs', 'Biceps', 'Shoulders', 'Upper Back']",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Eccentric Only Pull Up",
      primary_muscles: "Lats",
      secondary_muscles: "['Abs', 'Biceps', 'Shoulders', 'Upper Back']",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Close Grip Pull Up",
      primary_muscles: "Lats",
      secondary_muscles: "['Abs', 'Biceps', 'Shoulders', 'Upper Back']",
    },
    {
      equipment: "Bands",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Resistance Band Assisted Pull Up (From Knee)",
      primary_muscles: "Lats",
      secondary_muscles: "['Abs', 'Biceps', 'Shoulders', 'Upper Back']",
    },
    {
      equipment: "Chains",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Weighted Chin Up",
      primary_muscles: "Lats",
      secondary_muscles: "['Abs', 'Biceps', 'Shoulders', 'Upper Back']",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Pull",
      mechanics: "Compound",
      name: "Underhand Close Grip Lat Pulldown",
      primary_muscles: "Lats",
      secondary_muscles: "['Biceps', 'Middle Back']",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Warmup",
      experience: "Beginner",
      force_type: "Static Stretching",
      mechanics: "Isolation",
      name: "Rack Lat Stretch",
      primary_muscles: "Lats",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bands",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Resistance Band Assisted Pull Up (From Foot)",
      primary_muscles: "Lats",
      secondary_muscles: "['Abs', 'Biceps', 'Shoulders', 'Upper Back']",
    },
    {
      equipment: "Machine",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Compound",
      name: "Lat Pulldown (Rope Extension)",
      primary_muscles: "Lats",
      secondary_muscles: "['Biceps', 'Middle Back', 'Shoulders']",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Pull Up with Leg Raise",
      primary_muscles: "Lats",
      secondary_muscles: "['Abs', 'Biceps', 'Shoulders', 'Upper Back']",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Close Grip Chin Up",
      primary_muscles: "Lats",
      secondary_muscles: "['Abs', 'Biceps', 'Shoulders', 'Upper Back']",
    },
    {
      equipment: "Medicine Ball",
      exercise_type: "Plyometrics",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Standing Overhead Medicine Ball Throw",
      primary_muscles: "Lats",
      secondary_muscles: "['Abs', 'Triceps', 'Upper Back']",
    },
    {
      equipment: "Machine",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Behind Neck Lat Pull Down",
      primary_muscles: "Lats",
      secondary_muscles: "['Abs', 'Biceps', 'Shoulders', 'Upper Back']",
    },
    {
      equipment: "Rope",
      exercise_type: "Strength",
      experience: "Advanced",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Arms Only Rope Climb",
      primary_muscles: "Lats",
      secondary_muscles: "['Abs', 'Biceps', 'Shoulders', 'Upper Back']",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Thibaudeau Kayak Row",
      primary_muscles: "Lats",
      secondary_muscles: "['Abs', 'Biceps', 'Shoulders', 'Upper Back']",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Archer Pull Up",
      primary_muscles: "Lats",
      secondary_muscles: "['Abs', 'Biceps', 'Shoulders', 'Upper Back']",
    },
    {
      equipment: "Medicine Ball",
      exercise_type: "Plyometrics",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Standing Overhead Medicine Ball Slam",
      primary_muscles: "Lats",
      secondary_muscles: "['Abs', 'Triceps', 'Upper Back']",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Advanced",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "L-Sit Pull Up",
      primary_muscles: "Lats",
      secondary_muscles: "['Abs', 'Biceps', 'Shoulders', 'Upper Back']",
    },
    {
      equipment: "Rings",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Skin the Cat",
      primary_muscles: "Lats",
      secondary_muscles: "['Abs', 'Biceps', 'Shoulders', 'Upper Back']",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Mixed Grip Chin Up",
      primary_muscles: "Lats",
      secondary_muscles: "['Abs', 'Biceps', 'Shoulders', 'Upper Back']",
    },
    {
      equipment: "Machine",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Compound",
      name: "Overhand Close Grip Lat Pulldown",
      primary_muscles: "Lats",
      secondary_muscles: "['Biceps', 'Middle Back', 'Shoulders']",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Eccentric Only Chin Up",
      primary_muscles: "Lats",
      secondary_muscles: "['Abs', 'Biceps', 'Shoulders', 'Upper Back']",
    },
    {
      equipment: "Foam Roll",
      exercise_type: "SMR",
      experience: "Beginner",
      force_type: "Compression",
      mechanics: "Isolation",
      name: "Lat Foam Rolling",
      primary_muscles: "Lats",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Compound",
      name: "Wide Grip Chin Up",
      primary_muscles: "Lats",
      secondary_muscles: "['Biceps', 'Middle Back', 'Shoulders']",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Advanced",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "L-Sit Chin Up",
      primary_muscles: "Lats",
      secondary_muscles: "['Abs', 'Biceps', 'Shoulders', 'Upper Back']",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Chin Up With Leg Raise",
      primary_muscles: "Lats",
      secondary_muscles: "['Abs', 'Biceps', 'Shoulders', 'Upper Back']",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Gironda Sternum Chin Up",
      primary_muscles: "Lats",
      secondary_muscles: "['Abs', 'Biceps', 'Shoulders', 'Triceps']",
    },
  ],
  num_exercises: 40,
};
