const shoulders = {
  exercises: [
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Dumbbell Lateral Raise",
      primary_muscles: "Shoulders",
      secondary_muscles: "[]",
    },
    {
      equipment: "Barbell",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Military Press (AKA Overhead Press)",
      primary_muscles: "Shoulders",
      secondary_muscles: "['Abs', 'Traps', 'Triceps']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Isolation",
      name: "Bent Over Dumbbell Reverse Fly",
      primary_muscles: "Shoulders",
      secondary_muscles: "['Traps', 'Triceps']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Seated Dumbbell Press",
      primary_muscles: "Shoulders",
      secondary_muscles: "['Traps', 'Triceps']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push",
      mechanics: "Compound",
      name: "Standing Dumbbell Press",
      primary_muscles: "Shoulders",
      secondary_muscles: "['Triceps']",
    },
    {
      equipment: "Machine",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push",
      mechanics: "Compound",
      name: "Smith Machine Shoulder Press",
      primary_muscles: "Shoulders",
      secondary_muscles: "['Triceps']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Seated Arnold Press",
      primary_muscles: "Shoulders",
      secondary_muscles: "['Traps', 'Triceps']",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Cable Face Pull",
      primary_muscles: "Shoulders",
      secondary_muscles: "['Traps', 'Upper Back']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Seated Dumbbell Lateral Raise",
      primary_muscles: "Shoulders",
      secondary_muscles: "[]",
    },
    {
      equipment: "Barbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Seated Barbell Shoulder Press",
      primary_muscles: "Shoulders",
      secondary_muscles: "['Traps', 'Triceps']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Isolation",
      name: "Seated Bent Over Dumbbell Reverse Fly",
      primary_muscles: "Shoulders",
      secondary_muscles: "['Traps', 'Triceps']",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Isolation",
      name: "Standing Cable Reverse Fly",
      primary_muscles: "Shoulders",
      secondary_muscles: "['Traps', 'Upper Back']",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Pull (Unilateral)",
      mechanics: "Isolation",
      name: "Single Arm Cable Lateral Raise (Crossbody)",
      primary_muscles: "Shoulders",
      secondary_muscles: "['Traps']",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Cable Lateral Raise",
      primary_muscles: "Shoulders",
      secondary_muscles: "[]",
    },
    {
      equipment: "Barbell",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Seated Behind the Neck Shoulder Press",
      primary_muscles: "Shoulders",
      secondary_muscles: "['Traps', 'Triceps']",
    },
    {
      equipment: "Machine",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Machine Shoulder Press",
      primary_muscles: "Shoulders",
      secondary_muscles: "['Traps', 'Triceps']",
    },
    {
      equipment: "Machine",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Isolation",
      name: "Machine Reverse Fly",
      primary_muscles: "Shoulders",
      secondary_muscles: "['Traps']",
    },
    {
      equipment: "Machine",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push",
      mechanics: "Isolation",
      name: "Machine Lateral Raise",
      primary_muscles: "Shoulders",
      secondary_muscles: "[]",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Standing Dumbbell Front Raise",
      primary_muscles: "Shoulders",
      secondary_muscles: "[]",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Push",
      mechanics: "Compound",
      name: "Standing Arnold Press",
      primary_muscles: "Shoulders",
      secondary_muscles: "[]",
    },
    {
      equipment: "Barbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Isolation",
      name: "Barbell Front Raise",
      primary_muscles: "Shoulders",
      secondary_muscles: "['Abs', 'Traps']",
    },
    {
      equipment: "Other",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Weight Plate Front Raise",
      primary_muscles: "Shoulders",
      secondary_muscles: "[]",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "One Arm Dumbbell Lateral Raise",
      primary_muscles: "Shoulders",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bands",
      exercise_type: "Activation",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Band Pull Apart",
      primary_muscles: "Shoulders",
      secondary_muscles: "['Traps', 'Upper Back']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Dumbbell Upright Row",
      primary_muscles: "Shoulders",
      secondary_muscles: "['Biceps', 'Traps', 'Upper Back']",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Cable Upright Row",
      primary_muscles: "Shoulders",
      secondary_muscles: "['Biceps', 'Traps', 'Upper Back']",
    },
    {
      equipment: "Machine",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Smith Machine Upright Row",
      primary_muscles: "Shoulders",
      secondary_muscles: "['Shoulders', 'Traps']",
    },
    {
      equipment: "Kettle Bells",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Kettlebell Halo",
      primary_muscles: "Shoulders",
      secondary_muscles: "['Traps', 'Upper Back']",
    },
    {
      equipment: "Barbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Push Press",
      primary_muscles: "Shoulders",
      secondary_muscles: "['Abs', 'Traps', 'Triceps']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Isolation",
      name: "Bent Over Rear Delt Fly (Head on Bench)",
      primary_muscles: "Shoulders",
      secondary_muscles: "['Traps', 'Triceps']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Seated Neutral Grip Dumbbell Press",
      primary_muscles: "Shoulders",
      secondary_muscles: "['Traps', 'Triceps']",
    },
    {
      equipment: "Barbell",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Push",
      mechanics: "Compound",
      name: "Clean Press",
      primary_muscles: "Shoulders",
      secondary_muscles: "['Glutes', 'Hamstrings', 'Lower Back', 'Triceps']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Dumbbell Reverse Fly On Incline Bench",
      primary_muscles: "Shoulders",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bands",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Isolation",
      name: "Banded Lateral Raise",
      primary_muscles: "Shoulders",
      secondary_muscles: "['Traps', 'Upper Back']",
    },
    {
      equipment: "Barbell",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Z Press",
      primary_muscles: "Shoulders",
      secondary_muscles: "['Traps', 'Triceps']",
    },
    {
      equipment: "Landmine",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Unilateral)",
      mechanics: "Compound",
      name: "Half Kneeling Landmine Press",
      primary_muscles: "Shoulders",
      secondary_muscles: "['Abs', 'Traps', 'Triceps']",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Isolation",
      name: "Bent Over Low Pulley Rear Delt Fly",
      primary_muscles: "Shoulders",
      secondary_muscles: "['Traps']",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull (Bilateral)",
      mechanics: "Compound",
      name: "Cable Front Raise (Bilateral)",
      primary_muscles: "Shoulders",
      secondary_muscles: "['Traps', 'Upper Back']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Pull (Bilateral)",
      mechanics: "Isolation",
      name: "Lateral Raise Partials",
      primary_muscles: "Shoulders",
      secondary_muscles: "['Traps', 'Upper Back']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Unilateral)",
      mechanics: "Compound",
      name: "Alternate Seated Dumbbell Press",
      primary_muscles: "Shoulders",
      secondary_muscles: "['Traps', 'Triceps']",
    },
  ],
  num_exercises: 40,
};
