const triceps = {
  exercises: [
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Isolation",
      name: "Straight Bar Tricep Extension",
      primary_muscles: "Triceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Isolation",
      name: "Rope Tricep Extension",
      primary_muscles: "Triceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Isolation",
      name: "Seated Dumbbell Tricep Extension",
      primary_muscles: "Triceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "EZ Bar",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Isolation",
      name: "EZ Bar Skullcrusher",
      primary_muscles: "Triceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Push",
      mechanics: "Isolation",
      name: "Lying Dumbbell Extension",
      primary_muscles: "Triceps",
      secondary_muscles: "['Chest', 'Shoulders']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Dumbbell Floor Press",
      primary_muscles: "Triceps",
      secondary_muscles: "['Chest', 'Shoulders']",
    },
    {
      equipment: "Barbell",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Push",
      mechanics: "Isolation",
      name: "Lying Barbell Tricep Extension (Skull Crusher)",
      primary_muscles: "Triceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Barbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Close Grip Bench Press",
      primary_muscles: "Triceps",
      secondary_muscles: "['Chest', 'Shoulders']",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push",
      mechanics: "Compound",
      name: "Tricep Dips",
      primary_muscles: "Triceps",
      secondary_muscles: "['Chest', 'Shoulders']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Isolation",
      name: "Two Arm Standing Dumbbell Extension",
      primary_muscles: "Triceps",
      secondary_muscles: "['Abs']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Isolation",
      name: "Bent Over Dumbbell Tricep Kickback",
      primary_muscles: "Triceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Barbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push",
      mechanics: "Isolation",
      name: "French Press",
      primary_muscles: "Triceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Other",
      exercise_type: "Strength",
      experience: "Advanced",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Weighted Tricep Dips",
      primary_muscles: "Triceps",
      secondary_muscles: "['Chest', 'Shoulders']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Push",
      mechanics: "Isolation",
      name: "One-Arm Standing Dumbbell Extension",
      primary_muscles: "Triceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push",
      mechanics: "Compound",
      name: "Bench Dip",
      primary_muscles: "Triceps",
      secondary_muscles: "['Shoulders']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push",
      mechanics: "Isolation",
      name: "Dumbbell Tricep Kickback",
      primary_muscles: "Triceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Barbell",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Push",
      mechanics: "Isolation",
      name: "Incline Skull Crusher",
      primary_muscles: "Triceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Barbell",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Push",
      mechanics: "Isolation",
      name: "Seated French Press",
      primary_muscles: "Triceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Isolation",
      name: "Reverse Grip Cable Tricep Extension",
      primary_muscles: "Triceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push",
      mechanics: "Isolation",
      name: "Standing Low Pulley Overhead Tricep Extension (Rope Extension)",
      primary_muscles: "Triceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Intermediate",
      force_type: "Push",
      mechanics: "Isolation",
      name: "One-Arm Seated Dumbbell Extension",
      primary_muscles: "Triceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push",
      mechanics: "Compound",
      name: "Close Grip Push Up",
      primary_muscles: "Triceps",
      secondary_muscles: "['Shoulders']",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Isolation",
      name: "High Pulley Overhead Tricep Extension (rope extension)",
      primary_muscles: "Triceps",
      secondary_muscles: "['Abs']",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push",
      mechanics: "Isolation",
      name: "One-Arm Cable Tricep Extension",
      primary_muscles: "Triceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Eccentric Only Dip",
      primary_muscles: "Triceps",
      secondary_muscles: "['Abs', 'Chest', 'Shoulders']",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Isolation",
      name: "Cable Tricep Extension With V-Bar",
      primary_muscles: "Triceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Kettle Bells",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Unilateral)",
      mechanics: "Compound",
      name: "One Arm Kettlebell Floor Press",
      primary_muscles: "Triceps",
      secondary_muscles: "['Abs', 'Chest', 'Shoulders']",
    },
    {
      equipment: "Barbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push",
      mechanics: "Isolation",
      name: "45 Degree Lying Tricep Extension",
      primary_muscles: "Triceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "EZ Bar",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Isolation",
      name: "Standing Overhead EZ Bar Tricep Extension",
      primary_muscles: "Triceps",
      secondary_muscles: "['Abs']",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push",
      mechanics: "Isolation",
      name: "High Pulley Overhead Tricep Extension",
      primary_muscles: "Triceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Pull",
      mechanics: "Isolation",
      name: "Reverse One-Arm Cable Tricep Extension",
      primary_muscles: "Triceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bands",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Compound",
      name: "Band Assisted Dip",
      primary_muscles: "Triceps",
      secondary_muscles: "['Chest', 'Shoulders']",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Unilateral)",
      mechanics: "Isolation",
      name: "One Arm Bent Over Dumbbell Tricep Kickback",
      primary_muscles: "Triceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Isolation",
      name: "Incline Dumbbell Tricep Extension",
      primary_muscles: "Triceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Dumbbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Isolation",
      name: "Lying Pronated Dumbbell Tricep Extension",
      primary_muscles: "Triceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Machine",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Isolation",
      name: "Machine Tricep Extension",
      primary_muscles: "Triceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bands",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push (Bilateral)",
      mechanics: "Isolation",
      name: "Banded Tricep Extension",
      primary_muscles: "Triceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Cable",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push",
      mechanics: "Isolation",
      name: "Cable Tricep Kickback",
      primary_muscles: "Triceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Barbell",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push",
      mechanics: "Isolation",
      name: "Inline Bench French Press",
      primary_muscles: "Triceps",
      secondary_muscles: "[]",
    },
    {
      equipment: "Bodyweight",
      exercise_type: "Strength",
      experience: "Beginner",
      force_type: "Push",
      mechanics: "Compound",
      name: "Single Bench Dip",
      primary_muscles: "Triceps",
      secondary_muscles: "['Chest', 'Shoulders']",
    },
  ],
  num_exercises: 40,
};
